.github/actions/reusable-python-setup_poetry/action.yml, .github/workflows/reusable-python-pytest_unix_os.yml, .github/workflows/reusable-python-pytest_windows.yml, .github/workflows/reusable-python-static_analysis.yml
- Additional repository support for poetry
- Change default shell to 'bash -l {0}' and delete input named shell_type
Test with [python-poetry-template](https://github.com/MiraGeoscience/python-poetry-template/pull/28) and [geo-unsup-mapper](https://github.com/MiraGeoscience/geo-unsup-mapper/actions/runs/10167512418)
⚠️ It is necessary to update github reference before merging python-poetry-template or geo-unsup-mapper
=> DEVOPS-459: Additional repository support for poetry

.github/workflows/reusable-python-pytest_windows.yml
**DEVOPS-459 - Modify reusable-python-static_analys workflow to manage conda package**
=> DEVOPS-459: Correct value of repo_token in reusable-python-pytest_windows

.github/actions/reusable-python-publish_to_artifactory/action.yml, .github/workflows/reusable-python-publish_conda_package.yml, .github/workflows/reusable-python-publish_pypi_package.yml
**DEVOPS-511 - automate publish to PyPi from Github**
⚠️ Need to update reference before any merging
=> DEVOPS-511: automate publish to PyPi from Github

.github/workflows/reusable-python-publish_pypi_package.yml
**DEVOPS-511 - automate publish to PyPi from Github**
=> DEVOPS-511: Add an if condition on the repository-url

.github/workflows/reusable-python-build_poetry_package.yml
**DEVOPS-550 - Disable the poetry installation in publish pip package**
=> DEVOPS-550: Disable installation step in build poetry package workflow

.github/workflows/reusable-python-publish_pypi_package.yml
**DEVOPS-554 - Modify condition on publish on Artifactory in the github workflow**
=> DEVOPS-554: Correct condition on publish to Artifactory

.github/workflows/reusable-python-publish_conda_package.yml, .github/workflows/reusable-python-publish_pypi_package.yml
**DEVOPS-557 - Add a condition to disable publish workflows on forks**
=> DEVOPS-557: Add a condition on every jobs inside publish workflows

.github/workflows/pre-commit.yml, .github/workflows/reusable-pre_commit.yml
**DEVOPS-565 - simplify code to list modified files for pre-commit**
=> DEVOPS-565: fix pre-commit when ref has /

.github/actions/reusable-get_draft_release/action.yml, .github/actions/reusable-python-setup_conda/action.yml, .github/actions/reusable-python-setup_hatch/action.yml, .github/actions/reusable-python-setup_poetry/action.yml, .github/workflows/reusable-python-publish_conda_package.yml, .github/workflows/reusable-python-publish_pypi_package.yml, .github/workflows/reusable-python-release_conda_assets.yml, .github/workflows/reusable-python-release_pypi_assets.yml
**DEVOPS-571 - add python packages in draft release, and publish to prod upon release**
=> DEVOPS-571: add python packages in draft release, and publish to prod upon release

.github/workflows/reusable-python-release_conda_assets.yml, .github/workflows/reusable-python-release_pypi_assets.yml
**DEVOPS-571 - add python packages in draft release, and publish to prod upon release**
=> DEVOPS-571: fixup

.github/workflows/reusable-python-build_poetry_package.yml, .github/workflows/reusable-python-build_setuptools_package.yml, .github/workflows/reusable-python-publish_pypi_package.yml
**GEOPY-1893 - geo-unsup-mapper is not loading the weights anymore**
=> GEOPY-1893: Add git lfs option to build_poetry and build_setuptools workflows

.github/workflows/reusable-python-publish_conda_package.yml
**GEOPY-1893 - geo-unsup-mapper is not loading the weights anymore**
=> GEOPY-1893: Modify git lfs default value

.github/workflows/reusable-python-publish_conda_package.yml, .github/workflows/reusable-python-release_conda_assets.yml
**DEVOPS-651 - error when publishing Python package to production upon release**
=> DEVOPS-651: Use new conda package extension

.github/workflows/reusable-pre_commit.yml
**DEVOPS-634 - pre-commit in github action sometimes fails to get base ref**
=> DEVOPS-634: try calculating fetch depth

.github/workflows/reusable-jira-issue_to_jira.yml
**DEVOPS-654 - broken automation creating JIRA issue from GitHub issue**
=> DEVOPS-654: try allowing empty jira components in issue_to_jira

.github/workflows/jira-pr_add_jira_summary.yml, .github/workflows/reusable-jira-pr_add_jira_summary.yml
**DEVOPS-692 - in PR auto title from JIRA does not only capture issue numbers**
=> DEVOPS-692: ignore non jira key-like that are no jira issues

.github/actions/reusable-python-setup_poetry/action.yml, .github/workflows/reusable-python-pytest.yml, .github/workflows/reusable-python-static_analysis.yml
**DEVOPS-694 - install extras with poetry in github pipelines**
=> DEVOPS-694: pass list of extras to poetry install action

.azure-pipelines/template-test-minimal-conda-env-install.yml
**GEOPY-1972 - new distribution for Analyst 4.5.1**
=> GEOPY-1972: new distribution for Analyst 4.5.1

.github/workflows/reusable-python-publish_conda_package.yml
**DEVOPS-668 - unify execution of conda for Windows and Linux from CI-tools pipelines**
using micromamba
=> DEVOPS-668: unify call to conda build on both OS

.azure-pipelines/template-test-minimal-conda-env-install.yml, .github/actions/reusable-python-setup_conda/action.yml, .github/workflows/reusable-python-build_poetry_package.yml, .github/workflows/reusable-python-build_setuptools_package.yml, .github/workflows/reusable-python-publish_pypi_package.yml, .github/workflows/reusable-python-publish_rattler_package.yml
**GEOPY-2049 - environment for coming pre-release**
=> GEOPY-2049: specify source path + using conda only

.github/actions/reusable-python-setup_conda/action.yml, .github/workflows/reusable-python-pytest.yml, .github/workflows/reusable-python-static_analysis.yml
**GEOPY-2241 - distribute orano-plate-interpreter for Analyst 4.6**
=> GEOPY-2241: distribute orano-plate-interpreter for Analyst 4.6

.github/workflows/reusable-jira-pr_add_jira_summary.yml
**DEVOPS-819 - PR title do not auto-populate from JIRA for petro-lingo**
=> DEVOPS-819: auth to JIRA with API token

.github/workflows/reusable-python-pytest.yml, .github/workflows/reusable-python-static_analysis.yml
**DEVOPS-584 - POC on pixi env for HPC**
=> DEVOPS-584: Update reusable-python workflow actions to use 'main' branch
