MiraGeoscience/CI-tools

.github/workflows/reusable-python-pytest_unix_os.yml, .github/workflows/reusable-python-pytest_windows.yml
**DEVOPS-459 - Modify reusable-python-static_analys workflow to manage conda package**
Test on [targeting-workflows](https://github.com/MiraGeoscience/targeting-workflow/actions/runs/10253328623?pr=107)
=> DEVOPS-459: Add a git lfs option for unix and windows pytest workflow

.github/workflows/reusable-python-publish_to_artifactory.yml
**DEVOPS-425 - auto-publish conda package to Artifactory upon version tag**
- Generate recipe with `grayskull`
- Build package with `conda build`  (so we cannot use lock file)
- Create an artifactory on github with our package (`.tar.gz`) which stay for a week (could be usefull if the uploading on artifactory doesn't work)
- Upload on the repo `analyst-dev-conda-local`
**Test on [geoapps-utils](https://github.com/MiraGeoscience/geoapps-utils/actions/runs/10221287753)**
=> DEVOPS-425: Add a python reusable workflow, which publish our package on Artifactory

.github/actions/reusable-python-setup_hatch/action.yml, .github/workflows/reusable-python-pytest_unix_os.yml, .github/workflows/reusable-python-pytest_windows.yml, .github/workflows/reusable-python-static_analysis.yml
**DEVOPS-439: Add hatch as package manager**
- Create an action named setup hatch
- Add a condition on the package manager inside `pytest_unix`, `pytest_windows` and `static_analysis`
✅ Test on `geoh5py` ([PR590](https://github.com/MiraGeoscience/geoh5py/actions/runs/10271459513?pr=590))
=> DEVOPS-439: Add hatch as package manager

.github/workflows/reusable-jira-issue_to_jira.yml, .github/workflows/reusable-jira-pr_add_jira_summary.yml, .github/workflows/reusable-pre_commit.yml, .github/workflows/reusable-python-publish_to_artifactory.yml, .github/workflows/reusable-python-pytest_unix_os.yml, .github/workflows/reusable-python-pytest_windows.yml, .github/workflows/reusable-python-static_analysis.yml
**DEVOPS-460 - have a timeout on github jobs**
Test on [geo-unsup-mapper](https://github.com/MiraGeoscience/geo-unsup-mapper/actions/runs/10339866844)
=> DEVOPS-460: Add a timeout for every jobs in reusable workflows

.github/workflows/reusable-pre_commit.yml
**DEVOPS-468 - in Analyst: use shared GitHub workflows and pre-commit hooks**
Since Insight, Integrator and GMS don't need to restrict verified files to those in the app_directory, I modify the workflow to integrate this feature without modifying each python project using this github workflow.
=> DEVOPS-468: Modify which files are checked during the pre-commit

.github/workflows/reusable-python-publish_package.yml, .github/workflows/reusable-python-publish_to_artifactory.yml
**DEVOPS-447 - auto-publish Python packages for PyPI**
- Modify publish package to enable `poetry` and `hatch` package to publish on Pypi and JFrog artifactory
- Use base64 encoded json string to dynamically manage repositories and their url and their credentials
:warning: Test on [geo-unsup-mapper](https://github.com/MiraGeoscience/geo-unsup-mapper/actions/runs/10393382804)
=> DEVOPS-447: Update publish package workflow with pypi package and multi repositories publishing

.github/workflows/reusable-pre_commit.yml, .github/workflows/reusable-python-publish_package.yml, .github/workflows/reusable-python-pytest_unix_os.yml, .github/workflows/reusable-python-pytest_windows.yml, .github/workflows/reusable-python-static_analysis.yml
**DEVOPS-483 - Add an optionnal timeout in reusable github workflow**
⚠️ Test on [simpeg-drivers](https://github.com/MiraGeoscience/simpeg-drivers/actions/runs/10634048675)
=> DEVOPS-483: Add a timeout_minutes input in all reusable workflows

.github/workflows/reusable-pre_commit.yml, .github/workflows/reusable-python-static_analysis.yml
**DEVOPS-473**
With pre-commit and static-analysis workflows, we need an option to choose which platform (windows, linux or macOS) we want to run our workflows on.
I choice to use the new version of our nomenclature (```lower-case```). This nomenclature is used in DEVOPS-466 and will be deploy on every workflow at the end of the week.
⚠️ Test on [geoh5py](https://github.com/MiraGeoscience/geoh5py/actions/runs/11019567479)
=> DEVOPS-473: Add the possibility to choice the platform for the reusable github workflows

.github/workflows/reusable-python-publish_conda_package.yml
**DEVOPS-553 - Correct build path in reusable-python-publish_conda_package**
=> DEVOPS-553: Add a output build-path inside Build conda package step

.github/workflows/reusable-python-publish_pypi_package.yml
**DEVOPS-552 - Correct Pypi url in reusable-python-publish_pip_package.yml**
=> DEVOPS-552: Update pypi url

.github/workflows/reusable-python-publish_pypi_package.yml
**DEVOPS-552 - Correct Pypi url in reusable-python-publish_pip_package.yml**
=> DEVOPS-552: Update test-pypi url

.github/workflows/reusable-python-publish_conda_package.yml
**DEVOPS-553 - Correct build path in reusable-python-publish_conda_package**
=> DEVOPS-553: Correct path in Download Artifact

.github/workflows/reusable-python-publish_pypi_package.yml
**DEVOPS-552 - Correct Pypi url in reusable-python-publish_pip_package.yml**
=> DEVOPS-552: Disable fail-fast option in the publishing job

.github/actions/reusable-python-setup_conda/action.yml, .github/workflows/reusable-python-publish_conda_package.yml
no cleanup for conda steps, as it was burning some minutes at the end of every job
Cleanup would be necessary only on custom executers: github starts clean every time, so no need to cleanup at the end.
=> no post-cleanup for conda

.github/workflows/reusable-pre_commit.yml
**DEVOPS-634 - pre-commit in github action sometimes fails to get base ref**
=> DEVOPS-634: simplification

.github/workflows/reusable-pre_commit.yml
**DEVOPS-634 - pre-commit in github action sometimes fails to get base ref**
Fix the reusable pre-commit action so that it works on branch pushes as well as PRs.
=> DEVOPS-634: fix pre commit run on push

.azure-pipelines/template-test-minimal-conda-env-install.yml
**DEVOPS-671 - test installation on Azure clean machine is not using artifactory channels**
testing from https://github.com/MiraGeoscience/geopy-distrib/commits/DEVOPS-671/
=> DEVOPS-671: collect the conda.lock files that do not specify channels

.azure-pipelines/template-test-minimal-conda-env-install.yml
**DEVOPS-719 - register image for under GitHub packages for CI-tools.docker-imageswindows-servercore-ltsc2022-micromamba**
=> DEVOPS-719: GitHub docker image

.docker-images/windows-servercore-ltsc2022-micromamba/Dockerfile, .github/actions/reusable-python-setup_conda/action.yml, .github/workflows/reusable-python-pytest.yml, .github/workflows/reusable-python-static_analysis.yml
**GA-8604 - update to micromamba 2**
=> GA-8604: use micromamba 2.1.0 in pipelines

.github/workflows/pre-commit.yml
**DEVOPS-784 - address security issues reported on CI-Tools pipelines**
Potential fix for [https://github.com/MiraGeoscience/CI-tools/security/code-scanning/3](https://github.com/MiraGeoscience/CI-tools/security/code-scanning/3)
To fix the issue, add a `permissions` block to the workflow. Since this is a pre-commit workflow, it likely only needs `contents: read` permissions to access repository contents. If additional permissions are required for the reusable workflow, they should be added explicitly based on its functionality.
The `permissions` block should be added at the root level of the workflow to apply to all jobs unless overridden. This ensures that the `GITHUB_TOKEN` has the least privileges necessary.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> DEVOPS-784: Potential fix for code scanning alert no. 3: Workflow does not contain permissions

.github/workflows/jira-issue_to_jira.yml
**DEVOPS-784 - address security issues reported on CI-Tools pipelines**
Potential fix for [https://github.com/MiraGeoscience/CI-tools/security/code-scanning/2](https://github.com/MiraGeoscience/CI-tools/security/code-scanning/2)
To fix the issue, add a `permissions` block to the workflow. This block should specify the minimal permissions required for the workflow to function correctly. Since the workflow interacts with JIRA issues, it likely requires `issues: write` permission. Other permissions should be set to `read` or omitted entirely if not needed.
The `permissions` block can be added at the root level of the workflow to apply to all jobs or at the job level for more granular control. In this case, adding it at the root level is sufficient.
_Suggested fixes powered by Copilot …
=> DEVOPS-784: Potential fix for code scanning alert no. 2: Workflow does not contain permissions

.github/workflows/jira-pr_add_jira_summary.yml
**DEVOPS-784 - address security issues reported on CI-Tools pipelines**
Potential fix for [https://github.com/MiraGeoscience/CI-tools/security/code-scanning/1](https://github.com/MiraGeoscience/CI-tools/security/code-scanning/1)
To fix the issue, we will add a `permissions` block at the root level of the workflow. This block will define the minimal permissions required for the workflow to function. Based on the context, the workflow likely interacts with pull requests and possibly repository contents. Therefore, we will set `contents: read` and `pull-requests: write` as the permissions. If additional permissions are required, they can be added later after verifying the workflow's requirements.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> DEVOPS-784: Potential fix for code scanning alert no. 1: Workflow does not contain permissions

.github/workflows/reusable-python-static_analysis.yml
**DEVOPS-822 - pylint runs twice on in PR, on modified files and then on all files**
=> DEVOPS-822: do not run pylint on all files in scope of a PullRequest
